
// ==============================================================
// 
// File    : XmlColors.js
// Summary : Pseudo xml data island.
//
// ==============================================================

// --------------------------------------------------------------
// Return an xml document parsed from the embedded string.
// Note two extra entries added to X11 set to block 16x16.
//
function GetXmlColorDoc()
{
  var xmlData = "\
  <Colors> \
  <ColorSet name='HTML Colors'>\
    <color name='Snow' value='#FFFAFA'/>\
    <color name='GhostWhite' value='#F8F8FF'/>\
    <color name='WhiteSmoke' value='#F5F5F5'/>\
    <color name='Gainsboro' value='#DCDCDC'/>\
    <color name='FloralWhite' value='#FFFAF0'/>\
    <color name='OldLace' value='#FDF5E6'/>\
    <color name='Linen' value='#FAF0E6'/>\
    <color name='AntiqueWhite' value='#FAEBD7'/>\
    <color name='PapayaWhip' value='#FFEFD5'/>\
    <color name='BlanchedAlmond' value='#FFEBCD'/>\
    <color name='Bisque' value='#FFE4C4'/>\
    <color name='PeachPuff' value='#FFDAB9'/>\
    <color name='NavajoWhite' value='#FFDEAD'/>\
    <color name='Moccasin' value='#FFE4B5'/>\
    <color name='Cornsilk' value='#FFF8DC'/>\
    <color name='Ivory' value='#FFFFF0'/>\
    <color name='LemonChiffon' value='#FFFACD'/>\
    <color name='Seashell' value='#FFF5EE'/>\
    <color name='Honeydew' value='#F0FFF0'/>\
    <color name='MintCream' value='#F5FFFA'/>\
    <color name='Azure' value='#F0FFFF'/>\
    <color name='AliceBlue' value='#F0F8FF'/>\
    <color name='Lavender' value='#E6E6FA'/>\
    <color name='LavenderBlush' value='#FFF0F5'/>\
    <color name='MistyRose' value='#FFE4E1'/>\
    <color name='White' value='#FFFFFF'/>\
    <color name='Black' value='#000000'/>\
    <color name='DarkSlateGray' value='#2F4F4F'/>\
    <color name='DimGray' value='#696969'/>\
    <color name='SlateGray' value='#708090'/>\
    <color name='LightSlateGray' value='#778899'/>\
    <color name='Gray' value='#C0C0C0'/>\
    <color name='MidnightBlue' value='#191970'/>\
    <color name='Navy' value='#000080'/>\
    <color name='CornflowerBlue' value='#6495ED'/>\
    <color name='DarkSlateBlue' value='#483D8B'/>\
    <color name='SlateBlue' value='#6A5ACD'/>\
    <color name='MediumSlateBlue' value='#7B68EE'/>\
    <color name='MediumBlue' value='#0000CD'/>\
    <color name='RoyalBlue' value='#4169E1'/>\
    <color name='Blue' value='#0000FF'/>\
    <color name='DodgerBlue' value='#1E90FF'/>\
    <color name='DeepSkyBlue' value='#00BFFF'/>\
    <color name='SkyBlue' value='#87CEEB'/>\
    <color name='LightSkyBlue' value='#87CEFA'/>\
    <color name='SteelBlue' value='#4682B4'/>\
    <color name='LightSteelBlue' value='#B0C4DE'/>\
    <color name='LightBlue' value='#ADD8E6'/>\
    <color name='PowderBlue' value='#B0E0E6'/>\
    <color name='PaleTurquoise' value='#AFEEEE'/>\
    <color name='DarkTurquoise' value='#00CED1'/>\
    <color name='MediumTurquoise' value='#48D1CC'/>\
    <color name='Turquoise' value='#40E0D0'/>\
    <color name='Cyan' value='#00FFFF'/>\
    <color name='LightCyan' value='#E0FFFF'/>\
    <color name='CadetBlue' value='#5F9EA0'/>\
    <color name='MediumAquamarine' value='#66CDAA'/>\
    <color name='Aquamarine' value='#7FFFD4'/>\
    <color name='DarkGreen' value='#006400'/>\
    <color name='DarkOliveGreen' value='#556B2F'/>\
    <color name='DarkSeaGreen' value='#8FBC8F'/>\
    <color name='SeaGreen' value='#2E8B57'/>\
    <color name='MediumSeaGreen' value='#3CB371'/>\
    <color name='LightSeaGreen' value='#20B2AA'/>\
    <color name='PaleGreen' value='#98FB98'/>\
    <color name='SpringGreen' value='#00FF7F'/>\
    <color name='LawnGreen' value='#7CFC00'/>\
    <color name='Green' value='#00FF00'/>\
    <color name='Chartreuse' value='#7FFF00'/>\
    <color name='MediumSpringGreen' value='#00FA9A'/>\
    <color name='GreenYellow' value='#ADFF2F'/>\
    <color name='LimeGreen' value='#32CD32'/>\
    <color name='YellowGreen' value='#9ACD32'/>\
    <color name='ForestGreen' value='#228B22'/>\
    <color name='OliveDrab' value='#6B8E23'/>\
    <color name='DarkKhaki' value='#BDB76B'/>\
    <color name='Khaki' value='#F0E68C'/>\
    <color name='PaleGoldenrod' value='#EEE8AA'/>\
    <color name='LightYellow' value='#FFFFE0'/>\
    <color name='Yellow' value='#FFFF00'/>\
    <color name='Gold' value='#FFD700'/>\
    <color name='Goldenrod' value='#DAA520'/>\
    <color name='DarkGoldenrod' value='#B8860B'/>\
    <color name='RosyBrown' value='#BC8F8F'/>\
    <color name='IndianRed' value='#CD5C5C'/>\
    <color name='SaddleBrown' value='#8B4513'/>\
    <color name='Sienna' value='#A0522D'/>\
    <color name='Peru' value='#CD853F'/>\
    <color name='Burlywood' value='#DEB887'/>\
    <color name='Beige' value='#F5F5DC'/>\
    <color name='Wheat' value='#F5DEB3'/>\
    <color name='SandyBrown' value='#F4A460'/>\
    <color name='Tan' value='#D2B48C'/>\
    <color name='Chocolate' value='#D2691E'/>\
    <color name='Firebrick' value='#B22222'/>\
    <color name='Brown' value='#A52A2A'/>\
    <color name='DarkSalmon' value='#E9967A'/>\
    <color name='Salmon' value='#FA8072'/>\
    <color name='LightSalmon' value='#FFA07A'/>\
    <color name='Orange' value='#FFA500'/>\
    <color name='DarkOrange' value='#FF8C00'/>\
    <color name='Coral' value='#FF7F50'/>\
    <color name='LightCoral' value='#F08080'/>\
    <color name='Tomato' value='#FF6347'/>\
    <color name='OrangeRed' value='#FF4500'/>\
    <color name='Red' value='#FF0000'/>\
    <color name='HotPink' value='#FF69B4'/>\
    <color name='DeepPink' value='#FF1493'/>\
    <color name='Pink' value='#FFC0CB'/>\
    <color name='LightPink' value='#FFB6C1'/>\
    <color name='PaleVioletRed' value='#DB7093'/>\
    <color name='Maroon' value='#B03060'/>\
    <color name='MediumVioletRed' value='#C71585'/>\
    <color name='Magenta' value='#FF00FF'/>\
    <color name='Violet' value='#EE82EE'/>\
    <color name='Plum' value='#DDA0DD'/>\
    <color name='Orchid' value='#DA70D6'/>\
    <color name='MediumOrchid' value='#BA55D3'/>\
    <color name='DarkOrchid' value='#9932CC'/>\
    <color name='DarkViolet' value='#9400D3'/>\
    <color name='BlueViolet' value='#8A2BE2'/>\
    <color name='Purple' value='#A020F0'/>\
    <color name='MediumPurple' value='#9370DB'/>\
    <color name='Thistle' value='#D8BFD8'/>\
  </ColorSet>\
  <ColorSet name='X11 Colors'>\
    <color name='Snow' value='#FFFAFA'/>\
    <color name='GhostWhite' value='#F8F8FF'/>\
    <color name='WhiteSmoke' value='#F5F5F5'/>\
    <color name='Gainsboro' value='#DCDCDC'/>\
    <color name='FloralWhite' value='#FFFAF0'/>\
    <color name='OldLace' value='#FDF5E6'/>\
    <color name='Linen' value='#FAF0E6'/>\
    <color name='AntiqueWhite' value='#FAEBD7'/>\
    <color name='PapayaWhip' value='#FFEFD5'/>\
    <color name='BlanchedAlmond' value='#FFEBCD'/>\
    <color name='Bisque' value='#FFE4C4'/>\
    <color name='PeachPuff' value='#FFDAB9'/>\
    <color name='NavajoWhite' value='#FFDEAD'/>\
    <color name='Moccasin' value='#FFE4B5'/>\
    <color name='Cornsilk' value='#FFF8DC'/>\
    <color name='Ivory' value='#FFFFF0'/>\
    <color name='LemonChiffon' value='#FFFACD'/>\
    <color name='Seashell' value='#FFF5EE'/>\
    <color name='Honeydew' value='#F0FFF0'/>\
    <color name='MintCream' value='#F5FFFA'/>\
    <color name='Azure' value='#F0FFFF'/>\
    <color name='AliceBlue' value='#F0F8FF'/>\
    <color name='Lavender' value='#E6E6FA'/>\
    <color name='LavenderBlush' value='#FFF0F5'/>\
    <color name='MistyRose' value='#FFE4E1'/>\
    <color name='White' value='#FFFFFF'/>\
    <color name='Black' value='#000000'/>\
    <color name='DarkSlateGray' value='#2F4F4F'/>\
    <color name='DimGray' value='#696969'/>\
    <color name='SlateGray' value='#708090'/>\
    <color name='LightSlateGray' value='#778899'/>\
    <color name='Gray' value='#C0C0C0'/>\
    <color name='LightGray' value='#D3D3D3'/>\
    <color name='MidnightBlue' value='#191970'/>\
    <color name='Navy' value='#000080'/>\
    <color name='NavyBlue' value='#000080'/>\
    <color name='CornflowerBlue' value='#6495ED'/>\
    <color name='DarkSlateBlue' value='#483D8B'/>\
    <color name='SlateBlue' value='#6A5ACD'/>\
    <color name='MediumSlateBlue' value='#7B68EE'/>\
    <color name='LightSlateBlue' value='#8470FF'/>\
    <color name='MediumBlue' value='#0000CD'/>\
    <color name='RoyalBlue' value='#4169E1'/>\
    <color name='Blue' value='#0000FF'/>\
    <color name='DodgerBlue' value='#1E90FF'/>\
    <color name='DeepSkyBlue' value='#00BFFF'/>\
    <color name='SkyBlue' value='#87CEEB'/>\
    <color name='LightSkyBlue' value='#87CEFA'/>\
    <color name='SteelBlue' value='#4682B4'/>\
    <color name='LightSteelBlue' value='#B0C4DE'/>\
    <color name='LightBlue' value='#ADD8E6'/>\
    <color name='PowderBlue' value='#B0E0E6'/>\
    <color name='PaleTurquoise' value='#AFEEEE'/>\
    <color name='DarkTurquoise' value='#00CED1'/>\
    <color name='MediumTurquoise' value='#48D1CC'/>\
    <color name='Turquoise' value='#40E0D0'/>\
    <color name='Cyan' value='#00FFFF'/>\
    <color name='LightCyan' value='#E0FFFF'/>\
    <color name='CadetBlue' value='#5F9EA0'/>\
    <color name='MediumAquamarine' value='#66CDAA'/>\
    <color name='Aquamarine' value='#7FFFD4'/>\
    <color name='DarkGreen' value='#006400'/>\
    <color name='DarkOliveGreen' value='#556B2F'/>\
    <color name='DarkSeaGreen' value='#8FBC8F'/>\
    <color name='SeaGreen' value='#2E8B57'/>\
    <color name='MediumSeaGreen' value='#3CB371'/>\
    <color name='LightSeaGreen' value='#20B2AA'/>\
    <color name='PaleGreen' value='#98FB98'/>\
    <color name='SpringGreen' value='#00FF7F'/>\
    <color name='LawnGreen' value='#7CFC00'/>\
    <color name='Green' value='#00FF00'/>\
    <color name='Chartreuse' value='#7FFF00'/>\
    <color name='MediumSpringGreen' value='#00FA9A'/>\
    <color name='GreenYellow' value='#ADFF2F'/>\
    <color name='LimeGreen' value='#32CD32'/>\
    <color name='YellowGreen' value='#9ACD32'/>\
    <color name='ForestGreen' value='#228B22'/>\
    <color name='OliveDrab' value='#6B8E23'/>\
    <color name='DarkKhaki' value='#BDB76B'/>\
    <color name='Khaki' value='#F0E68C'/>\
    <color name='PaleGoldenrod' value='#EEE8AA'/>\
    <color name='LightGoldenrodYel' value='#FAFAD2'/>\
    <color name='LightYellow' value='#FFFFE0'/>\
    <color name='Yellow' value='#FFFF00'/>\
    <color name='Gold' value='#FFD700'/>\
    <color name='LightGoldenrod' value='#EEDD82'/>\
    <color name='Goldenrod' value='#DAA520'/>\
    <color name='DarkGoldenrod' value='#B8860B'/>\
    <color name='RosyBrown' value='#BC8F8F'/>\
    <color name='IndianRed' value='#CD5C5C'/>\
    <color name='SaddleBrown' value='#8B4513'/>\
    <color name='Sienna' value='#A0522D'/>\
    <color name='Peru' value='#CD853F'/>\
    <color name='Burlywood' value='#DEB887'/>\
    <color name='Beige' value='#F5F5DC'/>\
    <color name='Wheat' value='#F5DEB3'/>\
    <color name='SandyBrown' value='#F4A460'/>\
    <color name='Tan' value='#D2B48C'/>\
    <color name='Chocolate' value='#D2691E'/>\
    <color name='Firebrick' value='#B22222'/>\
    <color name='Brown' value='#A52A2A'/>\
    <color name='DarkSalmon' value='#E9967A'/>\
    <color name='Salmon' value='#FA8072'/>\
    <color name='LightSalmon' value='#FFA07A'/>\
    <color name='Orange' value='#FFA500'/>\
    <color name='DarkOrange' value='#FF8C00'/>\
    <color name='Coral' value='#FF7F50'/>\
    <color name='LightCoral' value='#F08080'/>\
    <color name='Tomato' value='#FF6347'/>\
    <color name='OrangeRed' value='#FF4500'/>\
    <color name='Red' value='#FF0000'/>\
    <color name='HotPink' value='#FF69B4'/>\
    <color name='DeepPink' value='#FF1493'/>\
    <color name='Pink' value='#FFC0CB'/>\
    <color name='LightPink' value='#FFB6C1'/>\
    <color name='PaleVioletRed' value='#DB7093'/>\
    <color name='Maroon' value='#B03060'/>\
    <color name='MediumVioletRed' value='#C71585'/>\
    <color name='VioletRed' value='#D02090'/>\
    <color name='Magenta' value='#FF00FF'/>\
    <color name='Violet' value='#EE82EE'/>\
    <color name='Plum' value='#DDA0DD'/>\
    <color name='Orchid' value='#DA70D6'/>\
    <color name='MediumOrchid' value='#BA55D3'/>\
    <color name='DarkOrchid' value='#9932CC'/>\
    <color name='DarkViolet' value='#9400D3'/>\
    <color name='BlueViolet' value='#8A2BE2'/>\
    <color name='Purple' value='#A020F0'/>\
    <color name='MediumPurple' value='#9370DB'/>\
    <color name='Thistle' value='#D8BFD8'/>\
\
    <color name='White' value='#FFFFFF'/>\
    <color name='Black' value='#000000'/>\
\
    <color name='Snow1' value='#FFFAFA'/>\
    <color name='Snow2' value='#EEE9E9'/>\
    <color name='Snow3' value='#CDC9C9'/>\
    <color name='Snow4' value='#8B8989'/>\
    <color name='Seashell1' value='#FFF5EE'/>\
    <color name='Seashell2' value='#EEE5DE'/>\
    <color name='Seashell3' value='#CDC5BF'/>\
    <color name='Seashell4' value='#8B8682'/>\
    <color name='AntiqueWhite1' value='#FFEFDB'/>\
    <color name='AntiqueWhite2' value='#EEDFCC'/>\
    <color name='AntiqueWhite3' value='#CDC0B0'/>\
    <color name='AntiqueWhite4' value='#8B8378'/>\
    <color name='Bisque1' value='#FFE4C4'/>\
    <color name='Bisque2' value='#EED5B7'/>\
    <color name='Bisque3' value='#CDB79E'/>\
    <color name='Bisque4' value='#8B7D6B'/>\
    <color name='PeachPuff1' value='#FFDAB9'/>\
    <color name='PeachPuff2' value='#EECBAD'/>\
    <color name='PeachPuff3' value='#CDAF95'/>\
    <color name='PeachPuff4' value='#8B7765'/>\
    <color name='NavajoWhite1' value='#FFDEAD'/>\
    <color name='NavajoWhite2' value='#EECFA1'/>\
    <color name='NavajoWhite3' value='#CDB38B'/>\
    <color name='NavajoWhite4' value='#8B795E'/>\
    <color name='LemonChiffon1' value='#FFFACD'/>\
    <color name='LemonChiffon2' value='#EEE9BF'/>\
    <color name='LemonChiffon3' value='#CDC9A5'/>\
    <color name='LemonChiffon4' value='#8B8970'/>\
    <color name='Cornsilk1' value='#FFF8DC'/>\
    <color name='Cornsilk2' value='#EEE8CD'/>\
    <color name='Cornsilk3' value='#CDC8B1'/>\
    <color name='Cornsilk4' value='#8B8878'/>\
    <color name='Ivory1' value='#FFFFF0'/>\
    <color name='Ivory2' value='#EEEEE0'/>\
    <color name='Ivory3' value='#CDCDC1'/>\
    <color name='Ivory4' value='#8B8B83'/>\
    <color name='Honeydew1' value='#F0FFF0'/>\
    <color name='Honeydew2' value='#E0EEE0'/>\
    <color name='Honeydew3' value='#C1CDC1'/>\
    <color name='Honeydew4' value='#838B83'/>\
    <color name='LavenderBlush1' value='#FFF0F5'/>\
    <color name='LavenderBlush2' value='#EEE0E5'/>\
    <color name='LavenderBlush3' value='#CDC1C5'/>\
    <color name='LavenderBlush4' value='#8B8386'/>\
    <color name='MistyRose1' value='#FFE4E1'/>\
    <color name='MistyRose2' value='#EED5D2'/>\
    <color name='MistyRose3' value='#CDB7B5'/>\
    <color name='MistyRose4' value='#8B7D7B'/>\
    <color name='Azure1' value='#F0FFFF'/>\
    <color name='Azure2' value='#E0EEEE'/>\
    <color name='Azure3' value='#C1CDCD'/>\
    <color name='Azure4' value='#838B8B'/>\
    <color name='SlateBlue1' value='#836FFF'/>\
    <color name='SlateBlue2' value='#7A67EE'/>\
    <color name='SlateBlue3' value='#6959CD'/>\
    <color name='SlateBlue4' value='#473C8B'/>\
    <color name='RoyalBlue1' value='#4876FF'/>\
    <color name='RoyalBlue2' value='#436EEE'/>\
    <color name='RoyalBlue3' value='#3A5FCD'/>\
    <color name='RoyalBlue4' value='#27408B'/>\
    <color name='Blue1' value='#0000FF'/>\
    <color name='Blue2' value='#0000EE'/>\
    <color name='Blue3' value='#0000CD'/>\
    <color name='Blue4' value='#00008B'/>\
    <color name='DodgerBlue1' value='#1E90FF'/>\
    <color name='DodgerBlue2' value='#1C86EE'/>\
    <color name='DodgerBlue3' value='#1874CD'/>\
    <color name='DodgerBlue4' value='#104E8B'/>\
    <color name='SteelBlue1' value='#63B8FF'/>\
    <color name='SteelBlue2' value='#5CACEE'/>\
    <color name='SteelBlue3' value='#4F94CD'/>\
    <color name='SteelBlue4' value='#36648B'/>\
    <color name='DeepSkyBlue1' value='#00BFFF'/>\
    <color name='DeepSkyBlue2' value='#00B2EE'/>\
    <color name='DeepSkyBlue3' value='#009ACD'/>\
    <color name='DeepSkyBlue4' value='#00688B'/>\
    <color name='SkyBlue1' value='#87CEFF'/>\
    <color name='SkyBlue2' value='#7EC0EE'/>\
    <color name='SkyBlue3' value='#6CA6CD'/>\
    <color name='SkyBlue4' value='#4A708B'/>\
    <color name='LightSkyBlue1' value='#B0E2FF'/>\
    <color name='LightSkyBlue2' value='#A4D3EE'/>\
    <color name='LightSkyBlue3' value='#8DB6CD'/>\
    <color name='LightSkyBlue4' value='#607B8B'/>\
    <color name='SlateGray1' value='#C6E2FF'/>\
    <color name='SlateGray2' value='#B9D3EE'/>\
    <color name='SlateGray3' value='#9FB6CD'/>\
    <color name='SlateGray4' value='#6C7B8B'/>\
    <color name='LightSteelBlue1' value='#CAE1FF'/>\
    <color name='LightSteelBlue2' value='#BCD2EE'/>\
    <color name='LightSteelBlue3' value='#A2B5CD'/>\
    <color name='LightSteelBlue4' value='#6E7B8B'/>\
    <color name='LightBlue1' value='#BFEFFF'/>\
    <color name='LightBlue2' value='#B2DFEE'/>\
    <color name='LightBlue3' value='#9AC0CD'/>\
    <color name='LightBlue4' value='#68838B'/>\
    <color name='LightCyan1' value='#E0FFFF'/>\
    <color name='LightCyan2' value='#D1EEEE'/>\
    <color name='LightCyan3' value='#B4CDCD'/>\
    <color name='LightCyan4' value='#7A8B8B'/>\
    <color name='PaleTurquoise1' value='#BBFFFF'/>\
    <color name='PaleTurquoise2' value='#AEEEEE'/>\
    <color name='PaleTurquoise3' value='#96CDCD'/>\
    <color name='PaleTurquoise4' value='#668B8B'/>\
    <color name='CadetBlue1' value='#98F5FF'/>\
    <color name='CadetBlue2' value='#8EE5EE'/>\
    <color name='CadetBlue3' value='#7AC5CD'/>\
    <color name='CadetBlue4' value='#53868B'/>\
    <color name='Turquoise1' value='#00F5FF'/>\
    <color name='Turquoise2' value='#00E5EE'/>\
    <color name='Turquoise3' value='#00C5CD'/>\
    <color name='Turquoise4' value='#00868B'/>\
    <color name='Cyan1' value='#00FFFF'/>\
    <color name='Cyan2' value='#00EEEE'/>\
    <color name='Cyan3' value='#00CDCD'/>\
    <color name='Cyan4' value='#008B8B'/>\
    <color name='DarkSlateGray1' value='#97FFFF'/>\
    <color name='DarkSlateGray2' value='#8DEEEE'/>\
    <color name='DarkSlateGray3' value='#79CDCD'/>\
    <color name='DarkSlateGray4' value='#528B8B'/>\
    <color name='Aquamarine1' value='#7FFFD4'/>\
    <color name='Aquamarine2' value='#76EEC6'/>\
    <color name='Aquamarine3' value='#66CDAA'/>\
    <color name='Aquamarine4' value='#458B74'/>\
    <color name='DarkSeaGreen1' value='#C1FFC1'/>\
    <color name='DarkSeaGreen2' value='#B4EEB4'/>\
    <color name='DarkSeaGreen3' value='#9BCD9B'/>\
    <color name='DarkSeaGreen4' value='#698B69'/>\
    <color name='SeaGreen1' value='#54FF9F'/>\
    <color name='SeaGreen2' value='#4EEE94'/>\
    <color name='SeaGreen3' value='#43CD80'/>\
    <color name='SeaGreen4' value='#2E8B57'/>\
    <color name='PaleGreen1' value='#9AFF9A'/>\
    <color name='PaleGreen2' value='#90EE90'/>\
    <color name='PaleGreen3' value='#7CCD7C'/>\
    <color name='PaleGreen4' value='#548B54'/>\
    <color name='SpringGreen1' value='#00FF7F'/>\
    <color name='SpringGreen2' value='#00EE76'/>\
    <color name='SpringGreen3' value='#00CD66'/>\
    <color name='SpringGreen4' value='#008B45'/>\
    <color name='Green1' value='#00FF00'/>\
    <color name='Green2' value='#00EE00'/>\
    <color name='Green3' value='#00CD00'/>\
    <color name='Green4' value='#008B00'/>\
    <color name='Chartreuse1' value='#7FFF00'/>\
    <color name='Chartreuse2' value='#76EE00'/>\
    <color name='Chartreuse3' value='#66CD00'/>\
    <color name='Chartreuse4' value='#458B00'/>\
    <color name='OliveDrab1' value='#C0FF3E'/>\
    <color name='OliveDrab2' value='#B3EE3A'/>\
    <color name='OliveDrab3' value='#9ACD32'/>\
    <color name='OliveDrab4' value='#698B22'/>\
    <color name='DarkOliveGreen1' value='#CAFF70'/>\
    <color name='DarkOliveGreen2' value='#BCEE68'/>\
    <color name='DarkOliveGreen3' value='#A2CD5A'/>\
    <color name='DarkOliveGreen4' value='#6E8B3D'/>\
    <color name='Khaki1' value='#FFF68F'/>\
    <color name='Khaki2' value='#EEE685'/>\
    <color name='Khaki3' value='#CDC673'/>\
    <color name='Khaki4' value='#8B864E'/>\
    <color name='LightGoldenrod1' value='#FFEC8B'/>\
    <color name='LightGoldenrod2' value='#EEDC82'/>\
    <color name='LightGoldenrod3' value='#CDBE70'/>\
    <color name='LightGoldenrod4' value='#8B814C'/>\
    <color name='LightYellow1' value='#FFFFE0'/>\
    <color name='LightYellow2' value='#EEEED1'/>\
    <color name='LightYellow3' value='#CDCDB4'/>\
    <color name='LightYellow4' value='#8B8B7A'/>\
    <color name='Yellow1' value='#FFFF00'/>\
    <color name='Yellow2' value='#EEEE00'/>\
    <color name='Yellow3' value='#CDCD00'/>\
    <color name='Yellow4' value='#8B8B00'/>\
    <color name='Gold1' value='#FFD700'/>\
    <color name='Gold2' value='#EEC900'/>\
    <color name='Gold3' value='#CDAD00'/>\
    <color name='Gold4' value='#8B7500'/>\
    <color name='Goldenrod1' value='#FFC125'/>\
    <color name='Goldenrod2' value='#EEB422'/>\
    <color name='Goldenrod3' value='#CD9B1D'/>\
    <color name='Goldenrod4' value='#8B6914'/>\
    <color name='DarkGoldenrod1' value='#FFB90F'/>\
    <color name='DarkGoldenrod2' value='#EEAD0E'/>\
    <color name='DarkGoldenrod3' value='#CD950C'/>\
    <color name='DarkGoldenrod4' value='#8B6508'/>\
    <color name='RosyBrown1' value='#FFC1C1'/>\
    <color name='RosyBrown2' value='#EEB4B4'/>\
    <color name='RosyBrown3' value='#CD9B9B'/>\
    <color name='RosyBrown4' value='#8B6969'/>\
    <color name='IndianRed1' value='#FF6A6A'/>\
    <color name='IndianRed2' value='#EE6363'/>\
    <color name='IndianRed3' value='#CD5555'/>\
    <color name='IndianRed4' value='#8B3A3A'/>\
    <color name='Sienna1' value='#FF8247'/>\
    <color name='Sienna2' value='#EE7942'/>\
    <color name='Sienna3' value='#CD6839'/>\
    <color name='Sienna4' value='#8B4726'/>\
    <color name='Burlywood1' value='#FFD39B'/>\
    <color name='Burlywood2' value='#EEC591'/>\
    <color name='Burlywood3' value='#CDAA7D'/>\
    <color name='Burlywood4' value='#8B7355'/>\
    <color name='Wheat1' value='#FFE7BA'/>\
    <color name='Wheat2' value='#EED8AE'/>\
    <color name='Wheat3' value='#CDBA96'/>\
    <color name='Wheat4' value='#8B7E66'/>\
    <color name='Tan1' value='#FFA54F'/>\
    <color name='Tan2' value='#EE9A49'/>\
    <color name='Tan3' value='#CD853F'/>\
    <color name='Tan4' value='#8B5A2B'/>\
    <color name='Chocolate1' value='#FF7F24'/>\
    <color name='Chocolate2' value='#EE7621'/>\
    <color name='Chocolate3' value='#CD661D'/>\
    <color name='Chocolate4' value='#8B4513'/>\
    <color name='Firebrick1' value='#FF3030'/>\
    <color name='Firebrick2' value='#EE2C2C'/>\
    <color name='Firebrick3' value='#CD2626'/>\
    <color name='Firebrick4' value='#8B1A1A'/>\
    <color name='Brown1' value='#FF4040'/>\
    <color name='Brown2' value='#EE3B3B'/>\
    <color name='Brown3' value='#CD3333'/>\
    <color name='Brown4' value='#8B2323'/>\
    <color name='Salmon1' value='#FF8C69'/>\
    <color name='Salmon2' value='#EE8262'/>\
    <color name='Salmon3' value='#CD7054'/>\
    <color name='Salmon4' value='#8B4C39'/>\
    <color name='LightSalmon1' value='#FFA07A'/>\
    <color name='LightSalmon2' value='#EE9572'/>\
    <color name='LightSalmon3' value='#CD8162'/>\
    <color name='LightSalmon4' value='#8B5742'/>\
    <color name='Orange1' value='#FFA500'/>\
    <color name='Orange2' value='#EE9A00'/>\
    <color name='Orange3' value='#CD8500'/>\
    <color name='Orange4' value='#8B5A00'/>\
    <color name='DarkOrange1' value='#FF7F00'/>\
    <color name='DarkOrange2' value='#EE7600'/>\
    <color name='DarkOrange3' value='#CD6600'/>\
    <color name='DarkOrange4' value='#8B4500'/>\
    <color name='Coral1' value='#FF7256'/>\
    <color name='Coral2' value='#EE6A50'/>\
    <color name='Coral3' value='#CD5B45'/>\
    <color name='Coral4' value='#8B3E2F'/>\
    <color name='Tomato1' value='#FF6347'/>\
    <color name='Tomato2' value='#EE5C42'/>\
    <color name='Tomato3' value='#CD4F39'/>\
    <color name='Tomato4' value='#8B3626'/>\
    <color name='OrangeRed1' value='#FF4500'/>\
    <color name='OrangeRed2' value='#EE4000'/>\
    <color name='OrangeRed3' value='#CD3700'/>\
    <color name='OrangeRed4' value='#8B2500'/>\
    <color name='Red1' value='#FF0000'/>\
    <color name='Red2' value='#EE0000'/>\
    <color name='Red3' value='#CD0000'/>\
    <color name='Red4' value='#8B0000'/>\
    <color name='DeepPink1' value='#FF1493'/>\
    <color name='DeepPink2' value='#EE1289'/>\
    <color name='DeepPink3' value='#CD1076'/>\
    <color name='DeepPink4' value='#8B0A50'/>\
    <color name='HotPink1' value='#FF6EB4'/>\
    <color name='HotPink2' value='#EE6AA7'/>\
    <color name='HotPink3' value='#CD6090'/>\
    <color name='HotPink4' value='#8B3A62'/>\
    <color name='Pink1' value='#FFB5C5'/>\
    <color name='Pink2' value='#EEA9B8'/>\
    <color name='Pink3' value='#CD919E'/>\
    <color name='Pink4' value='#8B636C'/>\
    <color name='LightPink1' value='#FFAEB9'/>\
    <color name='LightPink2' value='#EEA2AD'/>\
    <color name='LightPink3' value='#CD8C95'/>\
    <color name='LightPink4' value='#8B5F65'/>\
    <color name='PaleVioletRed1' value='#FF82AB'/>\
    <color name='PaleVioletRed2' value='#EE799F'/>\
    <color name='PaleVioletRed3' value='#CD6889'/>\
    <color name='PaleVioletRed4' value='#8B475D'/>\
    <color name='Maroon1' value='#FF34B3'/>\
    <color name='Maroon2' value='#EE30A7'/>\
    <color name='Maroon3' value='#CD2990'/>\
    <color name='Maroon4' value='#8B1C62'/>\
    <color name='VioletRed1' value='#FF3E96'/>\
    <color name='VioletRed2' value='#EE3A8C'/>\
    <color name='VioletRed3' value='#CD3278'/>\
    <color name='VioletRed4' value='#8B2252'/>\
    <color name='Magenta1' value='#FF00FF'/>\
    <color name='Magenta2' value='#EE00EE'/>\
    <color name='Magenta3' value='#CD00CD'/>\
    <color name='Magenta4' value='#8B008B'/>\
    <color name='Orchid1' value='#FF83FA'/>\
    <color name='Orchid2' value='#EE7AE9'/>\
    <color name='Orchid3' value='#CD69C9'/>\
    <color name='Orchid4' value='#8B4789'/>\
    <color name='Plum1' value='#FFBBFF'/>\
    <color name='Plum2' value='#EEAEEE'/>\
    <color name='Plum3' value='#CD96CD'/>\
    <color name='Plum4' value='#8B668B'/>\
    <color name='MediumOrchid1' value='#E066FF'/>\
    <color name='MediumOrchid2' value='#D15FEE'/>\
    <color name='MediumOrchid3' value='#B452CD'/>\
    <color name='MediumOrchid4' value='#7A378B'/>\
    <color name='DarkOrchid1' value='#BF3EFF'/>\
    <color name='DarkOrchid2' value='#B23AEE'/>\
    <color name='DarkOrchid3' value='#9A32CD'/>\
    <color name='DarkOrchid4' value='#68228B'/>\
    <color name='Purple1' value='#9B30FF'/>\
    <color name='Purple2' value='#912CEE'/>\
    <color name='Purple3' value='#7D26CD'/>\
    <color name='Purple4' value='#551A8B'/>\
    <color name='MediumPurple1' value='#AB82FF'/>\
    <color name='MediumPurple2' value='#9F79EE'/>\
    <color name='MediumPurple3' value='#8968CD'/>\
    <color name='MediumPurple4' value='#5D478B'/>\
    <color name='Thistle1' value='#FFE1FF'/>\
    <color name='Thistle2' value='#EED2EE'/>\
    <color name='Thistle3' value='#CDB5CD'/>\
    <color name='Thistle4' value='#8B7B8B'/>\
    <color name='Gray0' value='#000000'/>\
    <color name='Gray1' value='#030303'/>\
    <color name='Gray2' value='#050505'/>\
    <color name='Gray3' value='#080808'/>\
    <color name='Gray4' value='#0A0A0A'/>\
    <color name='Gray5' value='#0D0D0D'/>\
    <color name='Gray6' value='#0F0F0F'/>\
    <color name='Gray7' value='#121212'/>\
    <color name='Gray8' value='#141414'/>\
    <color name='Gray9' value='#171717'/>\
    <color name='Gray10' value='#1A1A1A'/>\
    <color name='Gray11' value='#1C1C1C'/>\
    <color name='Gray12' value='#1F1F1F'/>\
    <color name='Gray13' value='#212121'/>\
    <color name='Gray14' value='#242424'/>\
    <color name='Gray15' value='#262626'/>\
    <color name='Gray16' value='#292929'/>\
    <color name='Gray17' value='#2B2B2B'/>\
    <color name='Gray18' value='#2E2E2E'/>\
    <color name='Gray19' value='#303030'/>\
    <color name='Gray20' value='#333333'/>\
    <color name='Gray21' value='#363636'/>\
    <color name='Gray22' value='#383838'/>\
    <color name='Gray23' value='#3B3B3B'/>\
    <color name='Gray24' value='#3D3D3D'/>\
    <color name='Gray25' value='#404040'/>\
    <color name='Gray26' value='#424242'/>\
    <color name='Gray27' value='#454545'/>\
    <color name='Gray28' value='#474747'/>\
    <color name='Gray29' value='#4A4A4A'/>\
    <color name='Gray30' value='#4D4D4D'/>\
    <color name='Gray31' value='#4F4F4F'/>\
    <color name='Gray32' value='#525252'/>\
    <color name='Gray33' value='#545454'/>\
    <color name='Gray34' value='#575757'/>\
    <color name='Gray35' value='#595959'/>\
    <color name='Gray36' value='#5C5C5C'/>\
    <color name='Gray37' value='#5E5E5E'/>\
    <color name='Gray38' value='#616161'/>\
    <color name='Gray39' value='#636363'/>\
    <color name='Gray40' value='#666666'/>\
    <color name='Gray41' value='#696969'/>\
    <color name='Gray42' value='#6B6B6B'/>\
    <color name='Gray43' value='#6E6E6E'/>\
    <color name='Gray44' value='#707070'/>\
    <color name='Gray45' value='#737373'/>\
    <color name='Gray46' value='#757575'/>\
    <color name='Gray47' value='#787878'/>\
    <color name='Gray48' value='#7A7A7A'/>\
    <color name='Gray49' value='#7D7D7D'/>\
    <color name='Gray50' value='#7F7F7F'/>\
    <color name='Gray51' value='#828282'/>\
    <color name='Gray52' value='#858585'/>\
    <color name='Gray53' value='#878787'/>\
    <color name='Gray54' value='#8A8A8A'/>\
    <color name='Gray55' value='#8C8C8C'/>\
    <color name='Gray56' value='#8F8F8F'/>\
    <color name='Gray57' value='#919191'/>\
    <color name='Gray58' value='#949494'/>\
    <color name='Gray59' value='#969696'/>\
    <color name='Gray60' value='#999999'/>\
    <color name='Gray61' value='#9C9C9C'/>\
    <color name='Gray62' value='#9E9E9E'/>\
    <color name='Gray63' value='#A1A1A1'/>\
    <color name='Gray64' value='#A3A3A3'/>\
    <color name='Gray65' value='#A6A6A6'/>\
    <color name='Gray66' value='#A8A8A8'/>\
    <color name='Gray67' value='#ABABAB'/>\
    <color name='Gray68' value='#ADADAD'/>\
    <color name='Gray69' value='#B0B0B0'/>\
    <color name='Gray70' value='#B3B3B3'/>\
    <color name='Gray71' value='#B5B5B5'/>\
    <color name='Gray72' value='#B8B8B8'/>\
    <color name='Gray73' value='#BABABA'/>\
    <color name='Gray74' value='#BDBDBD'/>\
    <color name='Gray75' value='#BFBFBF'/>\
    <color name='Gray76' value='#C2C2C2'/>\
    <color name='Gray77' value='#C4C4C4'/>\
    <color name='Gray78' value='#C7C7C7'/>\
    <color name='Gray79' value='#C9C9C9'/>\
    <color name='Gray80' value='#CCCCCC'/>\
    <color name='Gray81' value='#CFCFCF'/>\
    <color name='Gray82' value='#D1D1D1'/>\
    <color name='Gray83' value='#D4D4D4'/>\
    <color name='Gray84' value='#D6D6D6'/>\
    <color name='Gray85' value='#D9D9D9'/>\
    <color name='Gray86' value='#DBDBDB'/>\
    <color name='Gray87' value='#DEDEDE'/>\
    <color name='Gray88' value='#E0E0E0'/>\
    <color name='Gray89' value='#E3E3E3'/>\
    <color name='Gray90' value='#E5E5E5'/>\
    <color name='Gray91' value='#E8E8E8'/>\
    <color name='Gray92' value='#EBEBEB'/>\
    <color name='Gray93' value='#EDEDED'/>\
    <color name='Gray94' value='#F0F0F0'/>\
    <color name='Gray95' value='#F2F2F2'/>\
    <color name='Gray96' value='#F5F5F5'/>\
    <color name='Gray97' value='#F7F7F7'/>\
    <color name='Gray98' value='#FAFAFA'/>\
    <color name='Gray99' value='#FCFCFC'/>\
    <color name='Gray100' value='#FFFFFF'/>\
  </ColorSet>\
  </Colors>";

  return (new DOMParser()).parseFromString(xmlData, 'text/xml');
}
